// AI quest board: 3 daily quests generated by a Groq "quest master" agent
// from your actual analytics (weak topics, failure modes). The LLM only picks
// parameters for a whitelist of verifiable templates — progress is always
// checked against the attempt log, never trusted from the model. Falls back
// to a seeded board offline.
import { getEnrichedAttempts, patternRadar, type EnrichedAttempt } from "./analytics";
import { getInventory, updateInventory } from "./inventory";
import { askText, hasGroq } from "../lib/groq";

export type QuestTemplate =
  | "solve_count"
  | "solve_topic"
  | "solve_difficulty"
  | "clean_solves"
  | "attempt_count"
  | "win_rematch";

export interface BoardQuest {
  label: string; // flavor text from the quest master
  template: QuestTemplate;
  topic?: string;
  difficulty?: string;
  count: number;
  reward: number; // coins
}

export interface Board {
  day: string;
  quests: BoardQuest[];
  ai: boolean; // generated by the agent (vs seeded fallback)
}

const KEY = "leetgraph.questboard.v1";
const TEMPLATES: QuestTemplate[] = [
  "solve_count",
  "solve_topic",
  "solve_difficulty",
  "clean_solves",
  "attempt_count",
  "win_rematch",
];

function dayKey(now = Date.now()): string {
  const d = new Date(now);
  return `${d.getFullYear()}-${d.getMonth() + 1}-${d.getDate()}`;
}

function hash(s: string): number {
  let h = 2166136261;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

function fallbackBoard(day: string): Board {
  const h = hash("board:" + day);
  const quests: BoardQuest[] = [
    { label: "Warm the engine: log 2 attempts today.", template: "attempt_count", count: 2, reward: 25 },
    { label: "Close the deal: solve 2 nodes.", template: "solve_count", count: 2, reward: 35 },
    h % 2 === 0
      ? { label: "No crutches: 1 clean solve (no AI, no hints).", template: "clean_solves", count: 1, reward: 40 }
      : { label: "Settle a score: win 1 rematch.", template: "win_rematch", count: 1, reward: 45 },
  ];
  return { day, quests, ai: false };
}

function readCache(): Board | null {
  try {
    const b = JSON.parse(localStorage.getItem(KEY) || "null") as Board | null;
    return b && b.day === dayKey() ? b : null;
  } catch {
    return null;
  }
}

export function getBoard(): Board {
  const cached = readCache();
  if (cached) return cached;
  const board = fallbackBoard(dayKey());
  localStorage.setItem(KEY, JSON.stringify(board));
  return board;
}

function sanitize(raw: unknown): BoardQuest[] | null {
  if (!Array.isArray(raw)) return null;
  const out: BoardQuest[] = [];
  for (const q of raw.slice(0, 3)) {
    const t = q?.template as QuestTemplate;
    if (!TEMPLATES.includes(t)) continue;
    out.push({
      label: String(q.label ?? "Quest").slice(0, 90),
      template: t,
      topic: q.topic ? String(q.topic).toLowerCase().slice(0, 30) : undefined,
      difficulty: q.difficulty ? String(q.difficulty).toUpperCase() : undefined,
      count: Math.max(1, Math.min(3, Number(q.count) || 1)),
      reward: Math.max(20, Math.min(60, Number(q.reward) || 30)),
    });
  }
  return out.length === 3 ? out : null;
}

// Ask the quest-master agent for today's board (once per day).
export async function refreshBoardAI(): Promise<Board | null> {
  if (!hasGroq()) return null;
  const cached = readCache();
  if (cached?.ai) return cached;

  const data = getEnrichedAttempts();
  const radar = patternRadar(data)
    .sort((a, b) => a.solveRate - b.solveRate)
    .slice(0, 4)
    .map((r) => `${r.topic}: ${r.solveRate}% solve rate`)
    .join("; ");
  const recentFails = data
    .filter((a) => !a.solved)
    .slice(-6)
    .map((a) => `${a.title} (${a.failureMode ?? "?"})`)
    .join("; ");
  const topics = [...new Set(data.flatMap((a) => a.topics))].slice(0, 20).join(", ");

  try {
    const raw = await askText(
      `You are the Quest Master of a roguelike LeetCode trainer. Design exactly 3 daily quests as a JSON array, tailored to the player's weaknesses. Each item: {"label": string (fun, <=90 chars, imperative), "template": one of ${JSON.stringify(TEMPLATES)}, "topic"?: string (only for solve_topic, MUST be from the player's topic list), "difficulty"?: "EASY"|"MEDIUM"|"HARD" (only for solve_difficulty), "count": 1-3, "reward": 20-60 coins (harder = more)}. Mix difficulty. Output ONLY the JSON array.`,
      `Player topics: ${topics || "arrays, strings"}\nWeakest patterns: ${radar || "none yet"}\nRecent failures: ${recentFails || "none"}`,
      500
    );
    const parsed = sanitize(JSON.parse(raw.replace(/^```[a-z]*\n?|```$/gm, "").trim()));
    if (!parsed) return null;
    const board: Board = { day: dayKey(), quests: parsed, ai: true };
    localStorage.setItem(KEY, JSON.stringify(board));
    return board;
  } catch (e) {
    console.warn("[questboard] AI generation failed, keeping fallback:", e);
    return null;
  }
}

// ---------------- progress + rewards ----------------

export interface QuestStatus {
  quest: BoardQuest;
  progress: number;
  done: boolean;
  claimed: boolean;
}

function todays(data: EnrichedAttempt[]): EnrichedAttempt[] {
  const day = dayKey();
  return data.filter((a) => dayKey(a.at) === day);
}

export function boardStatus(): QuestStatus[] {
  const board = getBoard();
  const all = getEnrichedAttempts();
  const today = todays(all);
  const solves = today.filter((a) => a.solved);
  // Rematch wins today: solved today where the previous attempt (ever) failed.
  const lastResult = new Map<string, boolean>();
  let rematchWins = 0;
  for (const a of all) {
    if (dayKey(a.at) === dayKey() && a.solved && lastResult.get(a.slug) === false) rematchWins++;
    lastResult.set(a.slug, a.solved);
  }
  const claimed = getInventory().questsClaimed;

  return board.quests.map((q, i) => {
    let progress = 0;
    switch (q.template) {
      case "solve_count":
        progress = solves.length;
        break;
      case "solve_topic":
        progress = solves.filter((a) => a.topics.some((t) => t.toLowerCase().includes(q.topic ?? ""))).length;
        break;
      case "solve_difficulty":
        progress = solves.filter((a) => a.difficulty === q.difficulty).length;
        break;
      case "clean_solves":
        progress = solves.filter((a) => !a.ai && !a.hints).length;
        break;
      case "attempt_count":
        progress = today.length;
        break;
      case "win_rematch":
        progress = rematchWins;
        break;
    }
    return {
      quest: q,
      progress: Math.min(progress, q.count),
      done: progress >= q.count,
      claimed: claimed.includes(`${board.day}:${i}`),
    };
  });
}

// Claim a completed quest's coin reward. Returns coins granted (or null).
export function claimQuest(idx: number): number | null {
  const board = getBoard();
  const status = boardStatus()[idx];
  if (!status || !status.done || status.claimed) return null;
  updateInventory((inv) => ({
    coins: inv.coins + status.quest.reward,
    questsClaimed: [...inv.questsClaimed, `${board.day}:${idx}`],
  }));
  return status.quest.reward;
}
