"use client"
// Auto-generated by boneyard vite plugin — do not edit
import { registerBones } from 'boneyard-js/react'

import _interview_room from './interview-room.bones.json'
import _problem_statement from './problem-statement.bones.json'

registerBones({
  "interview-room": _interview_room,
  "problem-statement": _problem_statement,
})
