import React from "react";
import ReactDOM from "react-dom/client";
import { configureBoneyard } from "boneyard-js/react";
import { App } from "./App";
import "./index.css";
// Captured skeletons (generated by the boneyard vite plugin).
import "./bones/registry";

// Brutalist bones: warm gray fill matching the neo palette.
configureBoneyard({
  color: "#e3dcc6",
  animate: "shimmer",
  shimmerColor: "#f5efdd",
  stagger: true,
  transition: 250,
});

ReactDOM.createRoot(document.getElementById("root")!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
